CREATE OR REPLACE FUNCTION corner11_ra(ra DOUBLE ,de DOUBLE ,size_ra DOUBLE ,size_de DOUBLE ) RETURNS DOUBLE  DETERMINISTIC
BEGIN
DECLARE d DOUBLE DEFAULT (ra + (size_ra/2)/ABS(COS(RADIANS(corner01_dec(de, size_de)))));
	IF d > 360 THEN 
		RETURN (d - 360.);
	ELSE 
		RETURN d;
	END IF;
END;
