CREATE OR REPLACE FUNCTION corner10_dec(de DOUBLE PRECISION,size_de DOUBLE PRECISION) RETURNS DOUBLE PRECISION IMMUTABLE 
AS $$
DECLARE 
  d DOUBLE PRECISION := (de - (size_de/2));
BEGIN
  RETURN corner00_dec(de, size_de);
END;
$$ LANGUAGE 'plpgsql';